In [17]:
""" 

    @Author: Likhitha S
    @Date: 10-10-2024 11:30
    @Last Modified by: Likhitha S
    @Last Modified time: 10-10-2024 11:30
    @Title:Write a Python program to change the data type of an array.  

"""

import numpy as np
import logging

def change_dtype(arr):
    """

        Description: 
            This function is used to find the common elements present in both the array.
        Parameters: 
            ar1 and arr2 are arrays came from the main method.
        return:
            It returns differed ele listed in new array.

    """
    
    logging.basicConfig(filename="common.log",level=logging.INFO, format=("%(asctime)s- %(levelname)s- %(message)s"))
    print(f"old array: {arr}, and it's type: {arr.dtype}")
    
    n_arr=arr.astype(np.float64)
    logging.info(f"an old array datatype changed to  {n_arr} and new datatype will be: {n_arr.dtype}")
    print(f"an old array datatype changed to  {n_arr} and new datatype will be: {n_arr.dtype}")
    return n_arr


def main():
    arr=np.array([[12,34,45],[39,65,78]],dtype=np.int32)
    res=change_dtype(arr)
    print(f" after changing the datatype: {arr} and {res.dtype}")
    
if __name__=="__main__":
    main()

old array: [[12 34 45]
 [39 65 78]], and it's type: int32
an old array datatype changed to  [[12. 34. 45.]
 [39. 65. 78.]] and new datatype will be: float64
 after changing the datatype: [[12 34 45]
 [39 65 78]] and float64
