In [14]:
""" 
    @Author: Likhitha S
    @Date: 10-10-2024 16:00
    @Last Modified by: Likhitha S
    @Last Modified time: 10-10-2024 16:00
    @Title: reate a 3x3 matrix with values ranging from 2 to 10.  
           
"""

import numpy as np

def main():
    """

        Description: 
            This function is used to create the 3*3 matrix.
        Parameters: 
            List ia used to store the list type and arr is used to hold the converted numpy array .
        return:
            It print the 3*3 matrix.

    """
    
    arr=np.array([[2,3,4], [5,6,7], [8, 9, 10]])
    print(arr)
    print("---or---")
    
    arr1=np.zeros((3,3))
    j=2
    for i in range (3):
        for k in range(3):
            arr1[i,k]=j
            j+=1
    print(arr1)
    
if __name__=="__main__":
    main()

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
---or---
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
