In [4]:
""" 

    @Author: Likhitha S
    @Date: 10-10-2024 19:00
    @Last Modified by: Likhitha S
    @Last Modified time: 10-10-2024 19:00
    @Title: Write a Python program to create an array which looks like below array.  

"""

import numpy as np
import logging

def create_array(arr):
    """

        Description: 
            This function is used to create an array with one's and zero's as specified pattern.
        Parameters: 
            arr ia an array passed from main method.
        return:
            It returns an updated array.

    """
    
    logging.basicConfig(filename="common.log", filemode='w', level=logging.DEBUG, format=("%(asctime)s- %(levelname)s- %(message)s"))
    for i in range(len(arr)):
        for j in range(len(arr)):
            if i>j:
                arr[i][j]=1
                
    logging.debug(f"updated array will be: {arr}")
    return arr    
        
    
    
def main():
    arr=np.zeros((4,3))
    n_arr=create_array(arr)
    print("Updated array:",n_arr)
    
    
    
if __name__=="__main__":
    main()

Updated array: [[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
