In [9]:
""" 

    @Author: Likhitha S
    @Date: 10-10-2024 19:00
    @Last Modified by: Likhitha S
    @Last Modified time: 10-10-2024 19:00
    @Title: Write a Python program to create an array which looks like below array.  

"""

import numpy as np
import logging

def concatenate_array(arr1, arr2):
    """

        Description: 
            This function is used to create an array with one's and zero's as specified pattern.
        Parameters: 
            arr ia an array passed from main method.
        return:
            It returns an updated array.

    """
    
    logging.basicConfig(filename="common.log", filemode='w', level=logging.DEBUG, format=("%(asctime)s- %(levelname)s- %(message)s"))
    # axis 1-> indecates the horizonal concatination
    arr= np.concatenate((arr1, arr2), axis=1)
    logging.debug(f"updated array will be: {arr}")
    return arr    
        
    
    
def main():
    arr1=np.array([[0,1,2],[3,4,5]])
    arr2=np.array([[6,7,8],[9,10,11]])
    n_arr=concatenate_array(arr1, arr2)
    print("Updated array:",n_arr)
    
    
    
if __name__=="__main__":
    main()

Updated array: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
