In [10]:
""" 

    @Author: Likhitha S
    @Date: 10-10-2024 16:45
    @Last Modified by: Likhitha S
    @Last Modified time: 10-10-2024 16:45
    @Title: Write a Python program to create a 2d array with 1 on the border and 0 inside.

"""

import numpy as np

def main():
    """

        Description: 
            This function is used to create the collection of ones in an array of 5*5.
        Parameters: 
            arr is used to store the one's element in it and to modify based on the position.
        return:
            It print the original and updated array.

    """
    
    arr= np.ones((5,5))
    print("original array:",arr)
    
    for i in range(1,4):
        for j in range(1,4):
            arr[i,j]=0
           
            
    print("updated array: ",arr)
    
if __name__=="__main__":
    main()

original array: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
updated array:  [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
