In [13]:
""" 

    @Author: Likhitha S
    @Date: 10-10-2024 17:20
    @Last Modified by: Likhitha S
    @Last Modified time: 10-10-2024 17:20
    @Title: Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.  

"""

import numpy as np
import logging

def create_checkboard(val):
    """

        Description: 
            This function is used to create the checkerboard pattern of 8*8 matrix.
        Parameters: 
            arr is used to store the array elements.
        return:
            It print the updated array.

    """
    
    checkboard=np.zeros((val,val), dtype=int)
    logging.debug(f"initial matrix:\n{checkboard}")
    
    for i in range(8):
        for j in range(8):
            checkboard[i][j]=(i+j)%2
            
    logging.debug(f"updated matrix:\n{checkboard}")
    return checkboard

def main():
    
    board=create_checkboard(8)
    print("checkerboard look's like:",board)
    
if __name__=="__main__":
    main()

checkerboard look's like: [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
